### ISSUE TITLE
face rotation angle？

### ISSUE THREAD

**Issue by andiconda** [Vangos/kinect-2-face-hd#1]
From the Kinect V2 face SDK, can we know the angle that head rotate?

**Comment by Vangos** [comment]
Microsoft is not providing an out-of-the-box method to calculate the rotation angle. However, you could do so by comparing the angle between the nose, the head, and the neck points in the 3D space.

**Comment by andiconda** [comment]
Thanks a lot~  By the way how can we get the 3D position of face key points?

**Comment by Vangos** [comment]
The coordinates of the [face vertices](https://github.com/Vangos/kinect-2-face-hd/blob/master/Kinect2FaceHD/Kinect2FaceHD_NET/MainWindow.xaml.cs#L109) are already in the 3D space.
